version: '3.8'

services:
  web:
    build: .
    container_name: financetracker
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=dashboard.settings
    volumes:
      - .:/app
      - db_data:/app/faster
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true

volumes:
  db_data:
